spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/attestation_db?useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: false
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:Q0hBTkdFX01FX0pXVF9TRUNSRVRfRk9SX0xPQ0FMX0RFVl9PTkxZX18xMjM0NTY3ODkw}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
